---
- hosts: all
  gather_facts: True
  vars_files: "./deploy-vars.yml"

  roles:
    - ansible-role-i3
  #   - ansible-role-patching # mostly leave enabled as it does a cache update on ubuntu repos
  #   - ansible-role-apps
  #   - ansible-role-docker
  #   - ansible-role-python
  #   - ansible-role-asdf
  #   # - golang
  #   - ansible-role-zsh
  #   - ansible-role-server-banners-prompts
  #   - ansible-role-code-server
    - ansible-role-vnc

#  tasks:
#    - name: Install tigetvnc
#      package:
#        name: tigervnc
#        state: latest
#      become: true
#
#    - name: Install i3
#      package:
#        name: i3-wm
#        state: latest
#      become: true
#
#    - name: "Create the remote /root/.vnc directory"
#      file:
#        path: /root/.vnc
#        mode: 0755
#        state: directory
#
#    - name: "Change the permission to 600 for /root/.vnc/passwd file"
#      file:
#        path: /root/.vnc/passwd
#        mode: 0600
#
#    - name: "Start & enable the vncserver"
#      systemd:
#        state: started
#        daemon_reload: yes
#        name: vncserver@:1
#        enabled: True
#