---
- hosts: all
  gather_facts: True
  vars_files: "./deploy-vars.yml"

  roles:
    - ansible-role-patching # mostly leave enabled as it does a cache update
    - ansible-role-xorg
    - ansible-role-i3
    - ansible-role-apps
    - ansible-role-docker
    - ansible-role-python
    - ansible-role-asdf
    - ansible-role-zsh
    - ansible-role-server-banners-prompts
    - ansible-role-code-server
    - ansible-role-vnc

  tasks:
    - name: Reboot VM
      reboot:
        reboot_timeout: 3600