---
- hosts: all
  gather_facts: True
  vars_files: "./deploy-vars.yml"

  roles:
    - ansible-role-i3
    - ansible-role-patching # mostly leave enabled as it does a cache update on ubuntu repos
    - ansible-role-apps
    - ansible-role-docker
    - ansible-role-python
    - ansible-role-asdf
    - golang
    - ansible-role-zsh
    - ansible-role-server-banners-prompts
    - ansible-role-code-server
    - ansible-role-vnc
